<<<<<<< HEAD
image: node:6.9.4
=======
image: node:7.4.0
>>>>>>> upstream/develop

stages:
  - test

before_script:
  - npm install -g gulp
  - npm install
  - apt-get update -y
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - apt-get install yarn -y
  - yarn add -D babel-jest babel-polyfill

test:
  stage: test
  script:
    - npm test
